language: node_js
node_js:
  - "20"

services:
  - mongodb

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm run test

branches:
  only:
    - main
    - develop

notifications:
  email:
    on_success: change
    on_failure: always
